name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '00 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [ "Release", "Debug", "RelWithDebInfo" ]
        CXX: [ "clang++", "g++" ]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: CXX=${{matrix.CXX}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.BUILD_TYPE}}
      



